language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6

install:
 - "git clone git://github.com/n1k0/casperjs.git"
 - "sudo ln -s `pwd`/casperjs/bin/casperjs /usr/local/bin"
   # This is a dependency of our Django test script
 - pip install argparse --use-mirrors
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
 - pip install mock
 - pip install flake8 coverage --use-mirrors
 - pip install django-timedeltafield

before_script:
    - "pep8 --ignore=E501 screamshot"
    - flake8 --ignore=E501 screamshot

script:
    - coverage run quicktest.py screamshot

after_success:
 - pip install coveralls
 - coveralls
